// Mock data with real music samples
import type { Song, Album, Artist, Video, Merchandise, Event, Category } from './supabase'

export const mockSongs: Song[] = [
  { id: '1', title: 'Summer Vibes', slug: 'summer-vibes', description: 'Upbeat summer track', artist_id: '1', album_id: '1', artist: { id: '1', stage_name: 'Bensound', user_id: '', bio: '', cover_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400', website: '', social_links: {}, monthly_listeners: 50000, total_streams: 100000, total_followers: 5000, verified: true, featured: true, created_at: '', updated_at: '' }, audio_url: 'https://www.bensound.com/bensound-music/bensound-summer.mp3', cover_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300', duration: 210, genre_id: null, price: 0, currency: 'ZMW', access: 'free', lyrics: '', isrc: '', is_featured: true, is_explicit: false, play_count: 15000, download_count: 0, created_at: '', updated_at: '', deleted_at: null },
  { id: '2', title: 'Night Drive', slug: 'night-drive', description: 'Chill electronic vibes', artist_id: '1', album_id: '1', artist: { id: '1', stage_name: 'Bensound', user_id: '', bio: '', cover_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400', website: '', social_links: {}, monthly_listeners: 50000, total_streams: 100000, total_followers: 5000, verified: true, featured: true, created_at: '', updated_at: '' }, audio_url: 'https://www.bensound.com/bensound-music/bensound-thelounge.mp3', cover_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300', duration: 185, genre_id: null, price: 10, currency: 'ZMW', access: 'premium', lyrics: '', isrc: '', is_featured: false, is_explicit: false, play_count: 12000, download_count: 0, created_at: '', updated_at: '', deleted_at: null },
  { id: '3', title: 'Electro Smile', slug: 'electro-smile', description: 'Happy electronic music', artist_id: '2', album_id: null, artist: { id: '2', stage_name: 'Free Music', user_id: '', bio: '', cover_image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400', website: '', social_links: {}, monthly_listeners: 30000, total_streams: 80000, total_followers: 3000, verified: false, featured: true, created_at: '', updated_at: '' }, audio_url: 'https://www.bensound.com/bensound-music/bensound-electricsoul.mp3', cover_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300', duration: 245, genre_id: null, price: 10, currency: 'ZMW', access: 'premium', lyrics: '', isrc: '', is_featured: true, is_explicit: false, play_count: 18000, download_count: 0, created_at: '', updated_at: '', deleted_at: null },
  { id: '4', title: 'Ukulele Adventure', slug: 'ukulele-adventure', description: 'Fun ukulele track', artist_id: '3', album_id: '2', artist: { id: '3', stage_name: 'Happy Rock', user_id: '', bio: '', cover_image_url: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=400', website: '', social_links: {}, monthly_listeners: 40000, total_streams: 90000, total_followers: 4000, verified: true, featured: false, created_at: '', updated_at: '' }, audio_url: 'https://www.bensound.com/bensound-music/bensound-ukulele.mp3', cover_url: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=300', duration: 165, genre_id: null, price: 10, currency: 'ZMW', access: 'premium', lyrics: '', isrc: '', is_featured: false, is_explicit: false, play_count: 9000, download_count: 0, created_at: '', updated_at: '', deleted_at: null },
  { id: '5', title: 'Acoustic Breeze', slug: 'acoustic-breeze', description: 'Relaxing acoustic guitar', artist_id: '4', album_id: null, artist: { id: '4', stage_name: 'Acoustic Dreams', user_id: '', bio: '', cover_image_url: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400', website: '', social_links: {}, monthly_listeners: 25000, total_streams: 60000, total_followers: 2000, verified: false, featured: false, created_at: '', updated_at: '' }, audio_url: 'https://www.bensound.com/bensound-music/bensound-acousticbreeze.mp3', cover_url: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=300', duration: 200, genre_id: null, price: 100, currency: 'ZMW', access: 'premium', lyrics: '', isrc: '', is_featured: false, is_explicit: false, play_count: 7500, download_count: 0, created_at: '', updated_at: '', deleted_at: null },
  { id: '6', title: 'Creative Minds', slug: 'creative-minds', description: 'Inspiring corporate music', artist_id: '1', album_id: '1', artist: { id: '1', stage_name: 'Bensound', user_id: '', bio: '', cover_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400', website: '', social_links: {}, monthly_listeners: 50000, total_streams: 100000, total_followers: 5000, verified: true, featured: true, created_at: '', updated_at: '' }, audio_url: 'https://www.bensound.com/bensound-music/bensound-creativeminds.mp3', cover_url: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=300', duration: 180, genre_id: null, price: 500, currency: 'ZMW', access: 'premium', lyrics: '', isrc: '', is_featured: true, is_explicit: false, play_count: 22000, download_count: 0, created_at: '', updated_at: '', deleted_at: null },
]

export const mockAlbums: Album[] = [
  { id: '1', title: 'Summer Vibes Album', slug: 'summer-vibes-album', description: 'Collection of summer vibes', artist_id: '1', artist: { id: '1', stage_name: 'Bensound', user_id: '', bio: '', cover_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400', website: '', social_links: {}, monthly_listeners: 50000, total_streams: 100000, total_followers: 5000, verified: true, featured: true, created_at: '', updated_at: '' }, cover_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300', genre_id: null, album_type: 'album', release_date: '2024-01-15', price: 0, currency: 'ZMW', access: 'free', track_count: 4, total_duration: 800, total_streams: 50000, is_featured: true, is_explicit: false, created_at: '', updated_at: '', deleted_at: null },
  { id: '2', title: 'Ukulele Dreams', slug: 'ukulele-dreams', description: 'Fun ukulele tracks', artist_id: '3', artist: { id: '3', stage_name: 'Happy Rock', user_id: '', bio: '', cover_image_url: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=400', website: '', social_links: {}, monthly_listeners: 40000, total_streams: 90000, total_followers: 4000, verified: true, featured: false, created_at: '', updated_at: '' }, cover_url: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=300', genre_id: null, album_type: 'ep', release_date: '2024-03-20', price: 100, currency: 'ZMW', access: 'premium', track_count: 3, total_duration: 500, total_streams: 35000, is_featured: false, is_explicit: false, created_at: '', updated_at: '', deleted_at: null },
]

export const mockVideos: Video[] = [
  { id: '1', title: 'Summer Vibes - Official Video', slug: 'summer-vibes-video', description: 'Official music video', artist_id: '1', artist: { id: '1', stage_name: 'Bensound', user_id: '', bio: '', cover_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400', website: '', social_links: {}, monthly_listeners: 50000, total_streams: 100000, total_followers: 5000, verified: true, featured: true, created_at: '', updated_at: '' }, song_id: null, video_url: '', thumbnail_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400', duration: 240, quality: {}, genre_id: null, price: 10, currency: 'ZMW', access: 'premium', view_count: 25000, download_count: 0, is_featured: true, is_music_video: true, created_at: '', updated_at: '', deleted_at: null },
]

export const mockArtists: Artist[] = [
  { id: '1', user_id: '', stage_name: 'Bensound', bio: 'Free music composer creating royalty-free tracks', cover_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400', website: '', social_links: {}, monthly_listeners: 50000, total_streams: 100000, total_followers: 5000, verified: true, featured: true, created_at: '', updated_at: '' },
  { id: '2', user_id: '', stage_name: 'Free Music', bio: 'Electronic music producer', cover_image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400', website: '', social_links: {}, monthly_listeners: 30000, total_streams: 80000, total_followers: 3000, verified: false, featured: true, created_at: '', updated_at: '' },
  { id: '3', user_id: '', stage_name: 'Happy Rock', bio: 'Fun and upbeat music maker', cover_image_url: 'https://images.unsplash.com/photo-1504898770365-14faca6a7320?w=400', website: '', social_links: {}, monthly_listeners: 40000, total_streams: 90000, total_followers: 4000, verified: true, featured: false, created_at: '', updated_at: '' },
  { id: '4', user_id: '', stage_name: 'Acoustic Dreams', bio: 'Acoustic guitarist and composer', cover_image_url: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400', website: '', social_links: {}, monthly_listeners: 25000, total_streams: 60000, total_followers: 2000, verified: false, featured: false, created_at: '', updated_at: '' },
]

export const mockMerchandise: Merchandise[] = [
  { id: '1', title: 'ZedVevo T-Shirt', slug: 'zedvevo-tshirt', description: 'Comfortable cotton t-shirt', category: 'Apparel', price: 29.99, currency: 'ZMW', stock: 50, sold_count: 120, images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400'], sizes: ['S', 'M', 'L', 'XL'], colors: ['Black', 'White', 'Blue'], is_active: true, is_featured: true, seller_id: '1', artist_id: null, created_at: '', updated_at: '', deleted_at: null },
  { id: '2', title: 'Artist Hoodie', slug: 'artist-hoodie', description: 'Warm and cozy hoodie', category: 'Apparel', price: 49.99, currency: 'ZMW', stock: 30, sold_count: 85, images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400'], sizes: ['S', 'M', 'L', 'XL'], colors: ['Black', 'Gray'], is_active: true, is_featured: false, seller_id: '1', artist_id: null, created_at: '', updated_at: '', deleted_at: null },
]

export const mockEvents: Event[] = [
  { id: '1', title: 'Summer Music Festival', slug: 'summer-music-festival', description: 'The biggest music event of the year', artist_id: '1', artist: { id: '1', user_id: '', stage_name: 'Bensound', bio: '', cover_image_url: '', website: '', social_links: {}, monthly_listeners: 50000, total_streams: 100000, total_followers: 5000, verified: true, featured: true, created_at: '', updated_at: '' }, venue: 'Central Park', address: '123 Park Ave', city: 'Lusaka', country: 'Zambia', banner_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800', event_date: '2026-08-15', doors_open: '18:00', ticket_price: 75, currency: 'ZMW', total_tickets: 500, tickets_sold: 320, is_active: true, is_featured: true, created_at: '', updated_at: '' },
]

export const mockCategories: Category[] = [
  { id: '1', name: 'Pop', slug: 'pop', description: '', icon: 'music', image_url: null, parent_id: null, sort_order: 1, is_active: true, created_at: '', updated_at: '' },
  { id: '2', name: 'Hip Hop', slug: 'hip-hop', description: '', icon: 'mic', image_url: null, parent_id: null, sort_order: 2, is_active: true, created_at: '', updated_at: '' },
  { id: '3', name: 'Electronic', slug: 'electronic', description: '', icon: 'radio', image_url: null, parent_id: null, sort_order: 3, is_active: true, created_at: '', updated_at: '' },
  { id: '4', name: 'R&B', slug: 'rnb', description: '', icon: 'headphones', image_url: null, parent_id: null, sort_order: 4, is_active: true, created_at: '', updated_at: '' },
  { id: '5', name: 'Rock', slug: 'rock', description: '', icon: 'guitar', image_url: null, parent_id: null, sort_order: 5, is_active: true, created_at: '', updated_at: '' },
  { id: '6', name: 'Jazz', slug: 'jazz', description: '', icon: 'music-2', image_url: null, parent_id: null, sort_order: 6, is_active: true, created_at: '', updated_at: '' },
]
