// Re-export all pages
export { default as HomePage } from './HomePage'
export { default as MusicPage } from './MusicPage'
export { default as SongPage } from './SongPage'
export { default as VideosPage } from './VideosPage'
export { default as VideoPage } from './VideoPage'
export { default as StorePage } from './StorePage'
export { default as MerchandisePage } from './MerchandisePage'
export { default as CartPage } from './CartPage'
export { default as ArtistsPage } from './ArtistsPage'
export { default as ArtistPage } from './ArtistPage'
export { default as LibraryPage } from './LibraryPage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as ForgotPasswordPage } from './ForgotPasswordPage'
export { default as ResetPasswordPage } from './ResetPasswordPage'
export { default as SettingsPage } from './SettingsPage'
export { default as BecomeArtistPage } from './BecomeArtistPage'
export { default as PlansPage } from './PlansPage'
export { default as CheckoutSuccessPage } from './CheckoutSuccessPage'
export { default as NotFoundPage } from './NotFoundPage'

// Artist Dashboard Pages
export { default as ArtistDashboard } from './artist/Dashboard'
export { default as ArtistUpload } from './artist/Upload'
export { default as ArtistAlbums } from './artist/Albums'
export { default as ArtistVideos } from './artist/Videos'
export { default as ArtistEvents } from './artist/Events'
export { default as ArtistMerchandise } from './artist/Merchandise'
export { default as ArtistAnalytics } from './artist/Analytics'

// Admin Dashboard Pages
export { default as AdminDashboard } from './admin/Dashboard'
export { default as AdminUsers } from './admin/Users'
export { default as AdminArtists } from './admin/Artists'
export { default as AdminSongs } from './admin/Songs'
export { default as AdminAlbums } from './admin/Albums'
export { default as AdminVideos } from './admin/Videos'
export { default as AdminCategories } from './admin/Categories'
export { default as AdminMerchandise } from './admin/Merchandise'
export { default as AdminPayments } from './admin/Payments'
export { default as AdminOrders } from './admin/Orders'
export { default as AdminSettings } from './admin/Settings'
